version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15
    container_name: postgres_eleicoes
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha_segura_123
      POSTGRES_DB: eleicoes_2024
    ports:
      - "5432:5432"
    volumes:
      # Isso cria uma pasta 'postgres_data' no seu PC para não perder dados se desligar o docker
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  # Interface Visual (Opcional - para ver os dados no navegador)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_eleicoes
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always